### ISSUE TITLE
report total mapEdits as count not km

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-contributions-stats-frontend#25]
[Screencast from 13.07.2023 14:59:03.webm](https://github.com/GIScience/ohsome-contributions-stats-frontend/assets/7045979/7278697d-6732-4bca-ac7e-c9c98623117a)

here it says `km`, but it should just be the number

**Comment by mrkhan** [comment]
resolved in [commit](https://github.com/GIScience/ohsome-contributions-stats-frontend/commit/aa0c4bb06ae864d67f8030cef93db5a0b8ca2235)
