### ISSUE TITLE
Enable links to the dashboard providing only the hashtag

### ISSUE THREAD

**Issue by ElJocho** [GIScience/ohsome-contributions-stats-frontend#29]
E.g. we want to be able to get statistics using the following link: https://demo.contributions-stats.ohsome.org/dashboard#hashtags=jpmc

**Comment by mrkhan** [comment]
I propose that the following scenario should be supported

1. No params - already works
2. Only `hashtags` provided 
3. `hashtags` and Time range (`start` and `end`)
4. Only Time range (`start` and `end`) provided 
5. All params provided - already works
