### ISSUE TITLE
adjust layout of big numbers

### ISSUE THREAD

**Issue by Hagellach37** [GIScience/ohsome-contributions-stats-frontend#38]
Hey,
from my perspective the layout of the "big numbers" section should look more like on the Missing Maps Website:

![image](https://github.com/GIScience/ohsome-contributions-stats-frontend/assets/7045979/ffb4e82e-e426-4c84-80d6-31a3973f784c)

* larger icon
* larger number
* smaller text/heading

currently it looks like this:

![image](https://github.com/GIScience/ohsome-contributions-stats-frontend/assets/7045979/6e700a27-cd19-42da-8e57-c0d543ce7888)

**Comment by ElJocho** [comment]
new look: 
![Screenshot from 2023-07-25 14-33-42](https://github.com/GIScience/ohsome-contributions-stats-frontend/assets/44268882/2ac36a70-0bc5-4b2b-b4d2-ef7cdcbf3de1)
